#+author: varabho
#+youtube_id:

* 2025-04-30
** Jataka 305: Sīlavimaṁsana Jātaka

([[https://suttacentral.net/ja305][SC]], [[https://www.digitalpalireader.online/_dprhtml/index.html?loc=k.13.0.0.3.0.4.m][DPR]], [[http://localhost:4848/suttas/s0513a3.att/pli/cst4?quote=natthi%2520loke%2520raho%2520n%25C4%2581m%25C4%2581ti%2520ida%25E1%25B9%2581%2520satth%25C4%2581%2520jetavane%2520viharanto&window_type=Sutta+Study][SSP]]) Jataka 305

#+begin_quote
Na atthi loke raho nāma pāpakammaṁ pakubbato,\\
passanti vanabhūtāni, taṁ bālo maññatī raho.
#+end_quote

** Jataka 305: Sīlavimaṁsana Jātaka (Jātakatthavaṇṇanā)

#+begin_quote
Atīte Bārāṇasiyaṁ Brahmadatte rajjaṁ kārente Bodhisatto brāhmaṇakule nibbattitvā vayappatto tatth'eva

Bārāṇasiyaṁ disāpāmokkhassa santike pañcannaṁ māṇavakasatānaṁ jeṭṭho hutvā sippaṁ uggaṇhi.
#+end_quote

| Atīte           | In the past (locative of time)                      |
| Bārāṇasiyaṁ    | in Bārāṇasī (locative)                              |
| Brahmadatte     | Brahmadatta (locative, "during the reign of")       |
| rajjāṁ kārente | ruling the kingdom (present participle of *karoti*) |
| vayappatto      | come of age (past participle)                       |
| māṇavako        | young boy                                           |
| jeṭṭho          | eldest                                              |
| hutvā           | having become (absolutive of *hoti*)                |
| sippaṁ         | craft                                               |
| uggaṇhi         | he learned (past tense)                             |

#+begin_quote
Ācariyassa vayappattadhītā atthi.

So cintesi: "imesaṁ māṇavakānaṁ sīlaṁ vīmaṁsitvā sīlasampannass'; etaṁ dassāmīti".
#+end_quote

| vīmaṁsitvā     | investigate, test                     |
| sīlasampannassa | to the virtuous one (genitive/dative) |
| etaṁ dassāmi   | I will give this                      |

#+begin_quote
so ekadivasaṁ māṇavake āmantetvā "tātā, mayhaṁ dhītā vayappattā

vivāhaṁ assā kāressāmi vatthālaṁkāraṁ laddhuṁ vaṭṭati

tumhe attano ñātakānaṁ apassantānaṁ thenetvā
#+end_quote

| vivāha          | giving of a daughter in marriage                           |
| vatthālaṁkāraṁ | cloths + ornaments   (alaṁ + karoti = make yourself ready) |
| theneti         | to steal [√then]                                           |

#+begin_quote
vatthālaṁkāre āharatha

kenaci adiṭṭham eva gaṇhāmi dassetvā ābhataṁ na gaṇhāmīti"

Te "sādhū" ti sampaṭicchitvā  tato paṭṭhāya ñātakānaṁ apassantānaṁ thenetvā
#+end_quote

| ābhataṁ      | brought   pp of ābharati |
| sampaṭicchati | to agree, accept         |
| paṭṭhāya      | since then...            |

#+begin_quote

vatthapilandhanādīni āharanti. ācariyo ābhataṁ ābhataṁ visuṁ visuṁ yeva ṭhapesi.

Bodhisatto na kiñci āhari Atha naṁ ācariyo āha:

"tvaṁ pana tāta na kiñci āharasīti"

"Āma ācariyā" ti

"Kasmā tātā" ti

"Tumhe kassaci passantassa ābhataṁ na gaṇhatha,

ahaṁ pana pāpakaraṇe raho na passāmīti"
#+end_quote

| ādi     | nt. etc.; and so on; and so forth; lit. beginning with                              |
| visuṁ  | ind. separately; singly; individually                                               |
| ṭhapesi | ṭhapeti 5: pr. (+acc) places; puts; stands; lit. causes to stand [√ṭhā + *āpe + ti] |

#+begin_quote
dīpento ime dve gāthā āha:

N’atthi loke raho nāma pāpakammaṁ pakubbato

passanti vanabhūtāni, taṁ bālo maññatī raho

Ahaṁ raho na passāmi, suññaṁ vāpi na vijjati

yattha aññaṁ na passāmi asuññaṁ hoti tam mayā ti
#+end_quote

| dīpento | dīpeti 1: pr. (+acc) explains; illustrates; illuminates; lit. shines [√dīp + *e + ti] |

** Commentaries about "Arahant"

Visuddhimagga I 198 ([[https://archive.org/details/Visuddhimagga/page/198/mode/2up?view=theater][PDF]]): Tattha ārakattā arīnaṁ... ([[https://www.digitalpalireader.online/_dprhtml/index.html?loc=x.0.7.0.0.0.0.m&query=tattha%20%C4%81rakatt%C4%81%20ar%C4%ABna%E1%B9%83&para=4][DPR]], [[http://localhost:4848/suttas/e0101n.mul/pli/cst4?quote=tattha%2520%25C4%2581rakatt%25C4%2581%2520ar%25C4%25ABna%25E1%25B9%2581&window_type=Sutta+Study][SSP]]) Bhagavā arahan ti veditabbo.

#+begin_quote
(125.) tattha ārakattā arīnaṁ arānañca hatattā paccayādīnaṁ arahattā pāpakaraṇe rahābhāvāti imehi tāva kāraṇehi so bhagavā _arahanti_ anussarati. ārakā hi so sabbakilesehi suvidūravidūre ṭhito maggena savāsanānaṁ kilesānaṁ viddhaṁsitattāti _ārakattā arahaṁ_.
#+end_quote

- “Because he is far away (āraka) [from the passions],
- because he has destroyed the enemies (ari) [i.e., the passions],
- because he has broken the spokes (ara) [of the wheel of existence],
- because he is worthy (araha) of receiving the necessities,
- because he stays apart from evil actions

for all these reasons the Blessed One is called Arahant.”

See also Majjhima, I, p. 280; Aṅguttara, IV, p. 145.

M I 280 ([[https://archive.org/details/dhatukatha-pts/PTS-Majjhima-Nikaya-Vol-I-Trenckner-1888/page/280/mode/2up?view=theater][PDF]]) is the end of MN 39 Mahāassapurasutta ([[https://suttacentral.net/mn39/pli/ms][SC]])

#+begin_quote
Kathañca, bhikkhave, bhikkhu arahaṁ hoti? Ārakāssa honti pāpakā akusalā dhammā, saṅkilesikā, ponobbhavikā, sadarā, dukkhavipākā, āyatiṁ, jātijarāmaraṇiyā. Evaṁ kho, bhikkhave, bhikkhu arahaṁ hotī”ti.
#+end_quote

A IV 145 ([[https://archive.org/details/dhatukatha-pts/PTS-Anguttara-Nikaya-part-IV-Hardy-1899/page/145/mode/2up?view=theater][PDF]]) is AN 7.92 Arahāsutta ([[https://suttacentral.net/an7.92/pli/ms][SC]])

#+begin_quote
“Ārakattā arahā hoti. Katamesaṁ sattannaṁ? Sakkāyadiṭṭhi ārakā hoti, vicikicchā ārakā hoti, sīlabbataparāmāso ārako hoti, rāgo ārako hoti, doso ārako hoti, moho ārako hoti, māno ārako hoti. Imesaṁ kho, bhikkhave, sattannaṁ dhammānaṁ ārakattā arahā hotī”ti.
#+end_quote

[[https://dpdict.net/?q=arahattamagga][arahattamagga]] (8920/dpd)

#+begin_quote
(PMa) kilesehi ārakattā, kilesārīnaṁ hatattā, saṁsāracakkassa arānaṁ hatattā, pāpakaraṇe rahābhāvā, paccay'ādīnaṁ arahattā arahaṁ, arahato bhāvo arahattaṁ. kiṁ taṁ? arahattaphalaṁ. arahattassa maggo arahattamaggo.
#+end_quote

[[https://dpdict.net/?q=arahant][arahant]] (8928/dpd)

#+begin_quote
(MNa) tehi ārakattā arahaṁ hoti, dūrībhūtattā'ti attho.

(SNa) ārakā kilesehī'ti arahanto.
#+end_quote
