#+author: mahabodhi
#+youtube_id:

* 2025-06-11
** MN 118: Ānāpānassatisutta (excerpts)

([[https://suttacentral.net/mn118/pli/ms][SC]], [[http://localhost:4848/suttas/mn118/pli/ms?window_type=Sutta+Study][SSP]]) Anki deck: [[https://drive.google.com/file/d/1m54FNTw_zZqbLGOt1ZBgwDpOVQWllKex/view?usp=drive_link][MN 118 Ānāpānassatisutta.apkg]]

#+begin_quote
Evaṁ me sutaṁ — ekaṁ samayaṁ bhagavā sāvatthiyaṁ viharati pubbārāme migāramātupāsāde

sambahulehi abhiññātehi abhiññātehi therehi sāvakehi saddhiṁ —

āyasmatā ca sāriputtena āyasmatā ca mahāmoggallānena āyasmatā ca mahākassapena \\
... mahākaccāyanena ... mahākoṭṭhikena ... mahākappinena ... mahācundena ... \\
anuruddhena ... revatena ... ānandena, aññehi ca abhiññātehi abhiññātehi therehi sāvakehi saddhiṁ.
#+end_quote

| ekaṁ samayaṁ           | on one occasion                                               |
| bhagavā                 | Sublime One; Blessed One; Fortunate One                       |
| viharati                | lives (in); dwells (in); stays (in)                           |
| pubbārāme               | Pubbarama, Eastern monastery                                  |
| abhiññātehi abhiññātehi | very well-known; famous; distinguished; lit. completely known |
| therehi                 | old; elderly; senior; lit. lasting                            |
| āyasmatā                | sir; venerable; reverend; [ā + √i > ay + *as + mant]          |

#+begin_quote
... Tena kho pana samayena bhagavā tadahuposathe pannarase pavāraṇāya puṇṇāya
puṇṇamāya rattiyā bhikkhusaṅghaparivuto abbhokāse nisinno hoti.

... Idhevāhaṁ sāvatthiyaṁ komudiṁ cātumāsiniṁ āgamessāmī'ti.

... Te ca navā bhikkhū therehi bhikkhūhi ovadiyamānā anusāsiyamānā uḷāraṁ pubbenāparaṁ visesaṁ jānanti.

... Tena kho pana samayena bhagavā tadahuposathe pannarase komudiyā cātumāsiniyā puṇṇāya puṇṇamāya rattiyā bhikkhusaṅghaparivuto abbhokāse nisinno hoti.

Atha kho bhagavā tuṇhībhūtaṁ tuṇhībhūtaṁ bhikkhusaṅghaṁ anuviloketvā bhikkhū āmantesi:

“Apalāpāyaṁ, bhikkhave, parisā; nippalāpāyaṁ, bhikkhave, parisā; suddhā sāre patiṭṭhitā.
#+end_quote

| parivuta (pp. +instr)       | surrounded (by); accompanied (by); together (with) [pari + √var + ta] |
| abbhokāsa (m.)              | open space; open air; wide open space [abhi + ava + √kās + a]         |
| āgameti (pr. +acc)          | waits (until); waits (for); (comm) expects [√āgam + *e + ti]          |
| anusāsiyamāna (prp. +instr) | being instructed (by); being taught (by) [anu + √sās + iya + māna]    |
| uḷāra (adj.)                | excellent; lofty; high; noble [ud + √ar + *a]                         |
| pubbenāpara (adj.)          | successive; lit. before then after [pubbena + apara]                  |
| visesa (m.)                 | distinction; attainment; superior state; eminence [vi + √sis + *a]    |
| anuviloketi                 | looks around; surveys [anu + vi + √lok + *e + ti]                     |
| apalāpa (adj.)              | free from chatter; without idle talk [na + pa + √lap + *a]            |
| suddha (pp.)                | clean; pure; white; lit. purified [√sudh + ta]                        |
| sāra (m.)                   | core; essence; heartwood                                              |
| patiṭṭhita (pp. +loc)       | firmly grounded (in); well established (in); [pati + √ṭhā + ita]      |

#+html: <div class="pagebreak"></div>

#+begin_quote
... Santi, bhikkhave, bhikkhū imasmiṁ bhikkhusaṅghe arahanto khīṇāsavā vusitavanto katakaraṇīyā ...

Santi, bhikkhave, bhikkhū imasmiṁ bhikkhusaṅghe catunnaṁ satipaṭṭhānānaṁ bhāvanānuyogamanuyuttā viharanti

-- evarūpāpi, bhikkhave, santi bhikkhū imasmiṁ bhikkhusaṅghe.

... catunnaṁ sammappadhānānaṁ ... catunnaṁ iddhipādānaṁ ... pañcannaṁ indriyānaṁ ...

pañcannaṁ balānaṁ ... sattannaṁ bojjhaṅgānaṁ ... ariyassa aṭṭhaṅgikassa maggassa

bhāvanānuyogamanuyuttā viharanti — evarūpāpi, bhikkhave, santi bhikkhū imasmiṁ bhikkhusaṅghe.

Santi, bhikkhave, bhikkhū imasmiṁ bhikkhusaṅghe mettābhāvanānuyogamanuyuttā viharanti ... \\
karuṇābhāvanānuyogamanuyuttā viharanti ... muditābhāvanānuyogamanuyuttā viharanti ... \\
upekkhābhāvanānuyogamanuyuttā viharanti ... asubhabhāvanānuyogamanuyuttā viharanti ... \\
aniccasaññābhāvanānuyogamanuyuttā viharanti — evarūpāpi, bhikkhave, santi bhikkhū imasmiṁ bhikkhusaṅghe.

Santi, bhikkhave, bhikkhū imasmiṁ bhikkhusaṅghe ānāpānassatibhāvanānuyogamanuyuttā viharanti.
#+end_quote

| santi                           | there are; there exist                                                   |
| satipaṭṭhānānaṁ                 | attending mindfully; being present with mindfulness                      |
| bhāvanānuyogamanuyuttā          | devoted to meditation practice; engaged in mental cultivation            |
| sammappadhāna                   | correct application of effort                                            |
| iddhipāda                       | basis for spiritual power                                                |
| indriyānaṁ                     | faculties                                                                |
| bojjhaṅgānaṁ                   | awakening factors                                                        |
| ariyassa aṭṭhaṅgikassa maggassa | of the noble eightfold path                                              |
| mettā/karuṇā/muditā/upekkhā     | goodwill/compassion/sympathetic joy/equanimity                           |
| asubha                          | (meditation on) ugliness; foulness; unattractiveness; lit. not beautiful |
| aniccasaññā                     | recognition of impermanence (in); perception of instability (in)         |

#+begin_quote
Ānāpānassati, bhikkhave, bhāvitā bahulīkatā mahapphalā hoti mahānisaṁsā.

Ānāpānassati, bhikkhave, bhāvitā bahulīkatā cattāro satipaṭṭhāne paripūreti.

Cattāro satipaṭṭhānā bhāvitā bahulīkatā satta bojjhaṅge paripūrenti.

Satta bojjhaṅgā bhāvitā bahulīkatā vijjāvimuttiṁ paripūrenti.
#+end_quote

| ānāpānassati   | mindfulness while breathing in and out, āna + apāna + sati                              |
| sati        | mindfulness; presence; recollection; awareness, √sar･1 a (remember)                     |
| bhāvitā        | cultivated; developed                                                                   |
| bahulīkatā     | practised often; repeated a lot; done again and again                                   |
| mahapphalā     | of great fruit; yielding good results                                                   |
| mahānisaṁsā   | of great benefit (to); highly profitable (for)                                          |
| satipaṭṭhāne   | attending mindfully; being present with mindfulness                                     |
| paripūreti     | fulfils; completes; accomplishes; lit. causes to fill                                   |
| sattabojjhaṅge | seven elements of awakening; seven factors of enlightenment                             |
| vijjāvimuttiṁ | liberation and understanding; release and discernment; (or) emancipation through wisdom |

#+html: <div class="pagebreak"></div>

#+begin_quote
Kathaṁ bhāvitā ca, bhikkhave, ānāpānassati kathaṁ bahulīkatā mahapphalā hoti mahānisaṁsā?

Idha, bhikkhave, bhikkhu araññagato vā rukkhamūlagato vā suññāgāragato vā

nisīdati pallaṅkaṁ ābhujitvā ujuṁ kāyaṁ paṇidhāya parimukhaṁ satiṁ upaṭṭhapetvā.

So satova assasati satova passasati.
#+end_quote

| araññagato         | gone to the forest; gone to the woods                                                   |
| rukkhamūlagato     | gone to the foot of a tree                                                              |
| suññāgāragato      | gone to an uninhabited place; gone to an empty dwelling, hut                            |
| nisīdati           | sits (on); sits down (in)                                                               |
| pallaṅkaṁ         | cross-legged sitting position; meditation posture                                       |
| ujuṁ              | straight; upright; erect                                                                |
| kāyaṁ             | body; physical body; physical process; lit. accumulation, √ci･5 nā (gather, accumulate) |
| parimukhaṁ        | as first priority; to the fore - (comm) at the tip of the nose or on the upper lip;     |
| upaṭṭhapetvā       | having established, having set up, having aroused, having generated                     |
| assasati/passasati | breathes in/out, √sas･1 a (breath)                                                      |

#+begin_quote
Dīghaṁ vā assasanto ‘dīghaṁ assasāmī’ti pajānāti, dīghaṁ vā passasanto ‘dīghaṁ passasāmī’ti pajānāti; \\
rassaṁ vā assasanto ‘rassaṁ assasāmī’ti pajānāti, rassaṁ vā passasanto ‘rassaṁ passasāmī’ti pajānāti;

‘sabbakāyapaṭisaṁvedī assasissāmī’ti sikkhati, ‘sabbakāyapaṭisaṁvedī passasissāmī’ti sikkhati; \\
‘passambhayaṁ kāyasaṅkhāraṁ assasissāmī’ti sikkhati, ‘passambhayaṁ kāyasaṅkhāraṁ passasissāmī’ti sikkhati.
#+end_quote

| dīghaṁ              | (of breathing) for a long time; deeply                                 |
| assasanto/passasanto | breathing in/out                                                       |
| pajānāti             | (he) knows; knows clearly; understands; distinguishes, √ñā･5 nā (know) |
| rassaṁ              | (of breathing) for a short time; shallowly                             |
| sikkhati             | learns; trains (in); practices, √sikkh･1 a (learn, train)              |
| passambhayaṁ        | calming; stilling; settling; becoming quiet; lit. causing to be calm   |
| kāyasaṅkhāraṁ       | physical process; bodily function; breathing                           |

#+begin_quote
Pītipaṭisaṁvedī ... sukhapaṭisaṁvedī ... cittasaṅkhārapaṭisaṁvedī ... passambhayaṁ cittasaṅkhāraṁ ...
#+end_quote

| pītipaṭisaṁvedī          | experiencing heartfelt joy; feeling delight; sensitive to happiness |
| sukhapaṭisaṁvedī         | ease; comfort; happiness; pleasure; contentment                     |
| cittasaṅkhārapaṭisaṁvedī | experiencing mental activity; observing thought formation;          |
|                          | sensitive to the mental processes;                                  |
| cittasaṅkhāraṁ           | mental activity; thought formation; (comm) feeling and perception   |

#+begin_quote
Cittapaṭisaṁvedī ... abhippamodayaṁ ... samādahaṁ ... vimocayaṁ ...
#+end_quote

| cittapaṭisaṁvedī | experiencing the mind; conscious of psyche; sensitive to the mind            |
| abhippamodayaṁ  | gladdening; pleasing; satisfying; lit. causing extreme happiness             |
| samādahaṁ       | (of the mind) composing; stabilising; collecting; lit. placing together here |
| vimocayaṁ       | setting free; detaching; disengaging; releasing; lit. making free            |

#+begin_quote
Aniccānupassī ... virāgānupassī ... nirodhānupassī ... \\
‘paṭinissaggānupassī assasissāmī’ti sikkhati, ‘paṭinissaggānupassī passasissāmī’ti sikkhati.

Evaṁ bhāvitā kho, bhikkhave, ānāpānassati evaṁ bahulīkatā mahapphalā hoti mahānisaṁsā.
#+end_quote

| aniccānupassī       | observing impermanence (of); watching instability (of) |
| virāgānupassī       | observing dispassion; watching fading of desire        |
| nirodhānupassī      | observing cessation; watching ending                   |
| paṭinissaggānupassī | observing letting go; watching relinquishment          |

#+begin_quote
Kathaṁ bhāvitā ca, bhikkhave, ānāpānassati kathaṁ bahulīkatā cattāro satipaṭṭhāne paripūreti?

... kāye kāyānupassī ... vedanāsu vedanānupassī ...

citte cittānupassī, bhikkhave, tasmiṁ samaye bhikkhu viharati ātāpī sampajāno

satimā vineyya loke abhijjhādomanassaṁ.

Nāhaṁ, bhikkhave, muṭṭhassatissa asampajānassa ānāpānassatiṁ vadāmi.
#+end_quote

| ātāpī (adj.)           | ardent; zealous; with continuous effort; lit. burning [ā + √tap + *ī] |
| sampajāna (adj.)       | clearly aware; fully knowing; [saṁ + pa + √ñā + nā + a]              |
| satimant (adj.)        | mindful; fully present; lit. having memory quality [√sar + ti + mant] |
| vineyya (ger.)         | removing; getting rid (of) [vi + √nī + *ya]; ger. of vineti           |
| abhijjhādomanassa (m.) | wanting and unhappiness; craving and aversion [abhijjhā + domanassa]  |
| muṭṭhassatī (adj.)     | unmindful; forgetful; lit. with forgotten memory [muṭṭha + sati + ī]  |

#+begin_quote
... dhammesu dhammānupassī, bhikkhave, tasmiṁ samaye bhikkhu viharati ātāpī sampajāno

satimā vineyya loke abhijjhādomanassaṁ.

So yaṁ taṁ abhijjhādomanassānaṁ pahānaṁ taṁ paññāya disvā sādhukaṁ ajjhupekkhitā hoti.

... cattāro satipaṭṭhānā ... satta bojjhaṅge paripūrenti ...
#+end_quote

| pahāna (nt. +gen)        | giving up (of); removal (of); abandoning (of) [pa + √hā + ana]                   |
| ajjhupekkhitar (m. +acc) | equanimous observer (of); who observes indifferently [adhi + upa + √ikkh + itar] |

#+begin_quote
Kathaṁ bhāvitā ca, bhikkhave, satta bojjhaṅgā kathaṁ bahulīkatā vijjāvimuttiṁ paripūrenti?

Idha, bhikkhave, bhikkhu satisambojjhaṅgaṁ bhāveti vivekanissitaṁ virāganissitaṁ nirodhanissitaṁ vossaggapariṇāmiṁ.
#+end_quote

| bhāveti (pr. +acc) | cultivates; develops; lit. causes to become [√bhū + *e + ti]; caus of bhavati  |
| viveka (m.)        | seclusion; solitude; disengagement; [vi + √vic + *a]                           |
| nissita (pp.)      | dependent (on); attached (to); supported (by); based (on); [ni + √si + ta]     |
| vossagga (m.)      | complete relinquishment; release; letting go; giving up [vi + ava + √sajj + a] |
| pariṇāmī (adj.)    | developing (into); ripening (in); culminating (in);                            |
|                    | maturing (in); inclining towards [pari + √nam + *ī]                            |

#+begin_quote
Dhammavicayasambojjhaṅgaṁ bhāveti ... vīriyasambojjhaṅgaṁ bhāveti ... pītisambojjhaṅgaṁ bhāveti ...

passaddhisambojjhaṅgaṁ bhāveti ... samādhisambojjhaṅgaṁ bhāveti ...

upekkhāsambojjhaṅgaṁ bhāveti vivekanissitaṁ virāganissitaṁ nirodhanissitaṁ vossaggapariṇāmiṁ.

Evaṁ bhāvitā kho, bhikkhave, satta bojjhaṅgā evaṁ bahulīkatā vijjāvimuttiṁ paripūrentī”ti.

Idamavoca bhagavā. Attamanā te bhikkhū bhagavato bhāsitaṁ abhinandunti.
#+end_quote

*** cittasaṅkhāra

MN 44: Cūḷavedallasutta

#+begin_quote
“Assāsapassāsā kho, āvuso visākha, kāyikā ete dhammā kāyappaṭibaddhā,
tasmā assāsapassāsā kāyasaṅkhāro.

“In-&-out breaths are bodily; these are things tied up with the body.
That’s why in-&-out breaths are bodily fabrications.

Pubbe kho, āvuso visākha, vitakketvā vicāretvā pacchā vācaṁ bhindati,
tasmā vitakkavicārā vacīsaṅkhāro.

Having first directed one’s thoughts and made an evaluation, one then breaks out into speech.
That’s why directed thought & evaluation are verbal fabrications.

Saññā ca vedanā ca cetasikā ete dhammā cittappaṭibaddhā,
tasmā saññā ca vedanā ca cittasaṅkhāro”ti.

Perceptions & feelings are mental; these are things tied up with the mind.
That’s why perceptions & feelings are mental fabrications.”

(Aj Thanissaro)
#+end_quote

*** vossaggapariṇāmiṁ

vossaggapariṇāmiṁ: fulfillment/maturity of surrender/letting go/release

What type of letting go?

vossaggārammaṇam: Jhāna is reached by making "letting go/release/surrender" ("vossagga") the meditation object (e.g. SN 48.10, MN 118).

#+begin_quote
Katamañca, bhikkhave, samādhindriyaṁ? Idha, bhikkhave, ariyasāvako vossaggārammaṇaṁ karitvā labhati samādhiṁ, labhati cittassa ekaggataṁ. So vivicceva kāmehi vivicca akusalehi dhammehi savitakkaṁ savicāraṁ vivekajaṁ pītisukhaṁ paṭhamaṁ jhānaṁ upasampajja viharati.
#+end_quote

*** vijjāvimuttiṁ

SN 45.42-47 ([[https://archive.org/details/dhatukatha-pts/PTS-Samyutta-Nikaya-Vol-5-Feer-1898/page/27/mode/2up][S V 28]]) Saṁyojanappahānādisuttachakka

#+begin_quote
“Sace vo, bhikkhave, aññatitthiyā paribbājakā evaṁ puccheyyuṁ: ‘kimatthiyaṁ, āvuso, samaṇe gotame brahmacariyaṁ vussatī’ti, evaṁ puṭṭhā tumhe, bhikkhave, tesaṁ aññatitthiyānaṁ paribbājakānaṁ evaṁ byākareyyātha:

“Bhikkhus, if wanderers of other sects ask you: ‘For what purpose, friends, is the holy life lived under the ascetic Gotama?’—being asked thus, you should answer them thus:

‘saṁyojanappahānatthaṁ kho, āvuso, bhagavati brahmacariyaṁ vussatī’ti …pe…

‘It is, friends, for the abandoning of the fetters …

‘anusayasamugghātanatthaṁ kho, āvuso, bhagavati brahmacariyaṁ vussatī’ti …pe…

for the uprooting of the underlying tendencies …

‘addhānapariññatthaṁ kho, āvuso, bhagavati brahmacariyaṁ vussatī’ti …pe…

for the full understanding of the course …

‘āsavānaṁ khayatthaṁ kho, āvuso, bhagavati brahmacariyaṁ vussatī’ti …pe…

for the destruction of the taints …

for the realization of the fruit of true knowledge and liberation …

‘vijjāvimuttiphalasacchikiriyatthaṁ kho, āvuso, bhagavati brahmacariyaṁ vussatī’ti …pe…

for the sake of knowledge and vision …

‘ñāṇadassanatthaṁ kho, āvuso, bhagavati brahmacariyaṁ vussatī’ti …pe….

for the sake of final Nibbāna without clinging that the holy life is lived under the Blessed One.’

(Bhikkhu Bodhi)
#+end_quote

* Notes :noexport:
** vossaggapariṇāmiṁ

maturity of surrender S. I, 88. (Page 652)

https://suttacentral.net/sn3.18/pli/ms Kalyāṇamittasutta

Idhānanda, bhikkhu sammādiṭṭhiṁ bhāveti vivekanissitaṁ virāganissitaṁ nirodhanissitaṁ vossaggapariṇāmiṁ, sammāsaṅkappaṁ bhāveti … sammāvācaṁ bhāveti … sammākammantaṁ bhāveti … sammāājīvaṁ bhāveti … sammāvāyāmaṁ bhāveti … sammāsatiṁ bhāveti … sammāsamādhiṁ bhāveti vivekanissitaṁ virāganissitaṁ nirodhanissitaṁ vossaggapariṇāmiṁ. Evaṁ kho, ānanda, bhikkhu kalyāṇamitto kalyāṇasahāyo kalyāṇasampavaṅko ariyaṁ aṭṭhaṅgikaṁ maggaṁ bhāveti, ariyaṁ aṭṭhaṅgikaṁ maggaṁ bahulīkaroti. Tadamināpetaṁ, ānanda, pariyāyena veditabbaṁ yathā sakalamevidaṁ brahmacariyaṁ—yadidaṁ kalyāṇamittatā kalyāṇasahāyatā kalyāṇasampavaṅkatāti.

** the complete list

kind of mindfulness → sense restraint, giving up
how great fruit? small fruit
intentional, instrument to develop

http://localhost:4848/suttas/sn54.6/en/sujato?window_type=Sutta+Search
“‘Atthesā, ariṭṭha, ānāpānassati, nesā natthī’ti vadāmi.
I do not say it is not, but...

** Bodhipakkhiyā dhammā

AN 6.17 Soppasutta (On Sleep)

http://localhost:4848/suttas/an6.17/en/sujato?window_type=Sutta+Search

What do you think, mendicants?

Taṁ kiṁ maññatha, bhikkhave,

Have you ever seen or heard

api nu tumhehi diṭṭhaṁ vā sutaṁ vā:

of an ascetic or brahmin who indulges in the pleasures of sleeping, lying down, and drowsing as much as they like? Their sense doors are unguarded, they eat too much, they’re not dedicated to wakefulness, they’re unable to discern skillful qualities, and they don’t pursue the development of the qualities that lead to awakening in the evening and toward dawn. Yet they realize the undefiled freedom of heart and freedom by wisdom in this very life. And they live having realized it with their own insight due to the ending of defilements.”

‘samaṇo vā brāhmaṇo vā yāvadatthaṁ seyyasukhaṁ passasukhaṁ middhasukhaṁ anuyutto indriyesu aguttadvāro bhojane amattaññū jāgariyaṁ ananuyutto avipassako kusalānaṁ dhammānaṁ pubbarattāpararattaṁ bodhipakkhiyānaṁ dhammānaṁ bhāvanānuyogaṁ ananuyutto āsavānaṁ khayā anāsavaṁ cetovimuttiṁ paññāvimuttiṁ diṭṭheva dhamme sayaṁ abhiññā sacchikatvā upasampajja viharanto’”ti?

“No, sir.”

“No hetaṁ, bhante”.

“Good, mendicants!

“Sādhu, bhikkhave.

I too have never seen or heard of such a thing.

Mayāpi kho etaṁ, bhikkhave, neva diṭṭhaṁ na sutaṁ:
