#+author: gambhiro
#+youtube_id: qBWt6fmVbyU

* 2025-01-22
** Exercise

#+latex: \renewcommand{\arraystretch}{1.6}

#+ATTR_LATEX: :center nil
| of the phenomenas (gen.pl. of dhamma)        | \fillin{5cm}{dhammānaṁ}   |
| by the sage (instr.sg. of muni)              | \fillin{5cm}{muninā}       |
| having seen (abs of √dis)                    | \fillin{5cm}{disvā}        |
| he taught (aor.sg. of desayati)              | \fillin{5cm}{desayi}       |
| having been delighted (by)                   | \fillin{5cm}{abhinanditvā} |
| he was released from (aor.sg. of muccati)    | \fillin{5cm}{mucci}        |
| they were released from (aor.pl. of muccati) | \fillin{5cm}{mucciṁsu}    |
| by the sickness (instr. of gelañña)          | \fillin{5cm}{gelaññena}    |

#+latex: \normalArrayStretch

** SN 46.16 Tatiyagilānasutta :anki:

([[https://suttacentral.net/sn46.16/pli/ms][SC]], [[https://www.digitalpalireader.online/_dprhtml/index.html?loc=s.4.0.0.1.1.5.m][DPR]], [[http://localhost:4848/suttas/sn46.16/pli/ms?window_type=Sutta+Study][SSP]])

#+latex: \vspace*{-\baselineskip}

#+begin_quote
Ekaṁ samayaṁ bhagavā rājagahe viharati veḷuvane kalandakanivāpe.

Tena kho pana samayena bhagavā ābādhiko hoti dukkhito bāḷhagilāno.

Atha kho āyasmā mahācundo yena bhagavā tenupasaṅkami;

upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ nisīdi.

Ekamantaṁ nisinnaṁ kho āyasmantaṁ mahācundaṁ bhagavā etadavoca:

“paṭibhantu taṁ, cunda, bojjhaṅgā”ti.
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| paṭibhāti | comes to mind; occurs (to); lit. speaks back | 40689/dpd | {{paṭibhantu}} taṁ, cunda, bojjhaṅgā. |
| √bhā      | shine, speak                                 |           |                                       |

#+latex: \vspace*{-\baselineskip}
#+latex: \enlargethispage{\baselineskip}

#+begin_quote
“Sattime, bhante, bojjhaṅgā ...

“Taggha, cunda, bojjhaṅgā; taggha, cunda, bojjhaṅgā”ti.

Idamavocāyasmā cundo. Samanuñño satthā ahosi. Vuṭṭhahi ca bhagavā tamhā ābādhā.

Tathāpahīno ca bhagavato so ābādho ahosī'ti.
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| samanuñña (adj.) | approving (of); consenting (to) | 59342/dpd | {{Samanuñño}} satthā ahosi. |
| satthā (m.)      | teacher; master; the Buddha     | 57894/dpd | Samanuñño {{satthā}} ahosi. |

\clearpage
\casesLegendHeaderBGHere

** Bojjhaṅga-paritta :anki:

#+begin_quote
Bojjhaṅgo sati-saṅkhāto / dhammānaṁ vicayo tathā

Viriyam-pīti-passaddhi / bojjhaṅgā ca tathā'pare

Samādh'upekkha-bojjhaṅgā / satt'ete sabba-dassinā

Muninā sammad-akkhātā / bhāvitā bahulīkatā

Saṁvattanti abhiññāya / nibbānāya ca bodhiyā

Etena sacca-vajjena / sotthi te hotu sabbadā
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| saṅkhāta (pp.) | reckoned; so called; pp of saṅkhāyati | 56755/dpd | bojjhaṅgo sati-{{saṅkhāto}}                    |
| vicaya (m.)    | investigation; examination            | 67414/dpd | dhammānaṁ {{vicayo}} tathā                    |
| para (pron.)   | other; another                        | 42854/dpd | bojjhaṅgā ca tathā'{{pare}}                    |
| dassī (adj.)   | seeing; perceiving; knowing           | 32148/dpd | sabba-{{dassinā}}                              |
| muni (m.)      | monk; sage; seer                      | 53022/dpd | {{muninā}} sammad-akkhātā                      |
| vajja (ptp.)   | speaking; saying; ptp of vadati       | 65708/dpd | Etena sacca-{{vajjena}} sotthi te hotu sabbadā |

#+begin_quote
Ekasmiṁ samaye nātho / moggallānañ-ca kassapaṁ

Gilāne dukkhite disvā / bojjhaṅge satta desayi

Te ca taṁ abhinanditvā / rogā mucciṁsu taṅ-khaṇe

Etena sacca-vajjena / sotthi te hotu sabbadā
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| nātha (m.)                | protector; lord; (The Buddha)                | 36192/dpd | Ekasmiṁ samaye {{nātho}}   |
| desayi (aor. +acc & +dat) | taught (to); explained (to); aor of desayati | 33981/dpd | bojjhaṅge satta {{desayi}}  |
| mucciṁsu (aor.3rd. +abl) | was released (from); aor of muccati          | 52830/dpd | rogā {{mucciṁsu}} taṅ-khaṇe |
| khaṇa (m.)                | moment; instant                              | 23317/dpd | rogā mucciṁsu taṅ-{{khaṇe}} |

\clearpage
\casesLegendHeaderBGHere

#+begin_quote
Ekadā dhamma-rājā pi / gelaññenābhipīḷito

Cundattherena tañ-ñeva / bhaṇāpetvāna sādaraṁ

Sammoditvā ca ābādhā / tamhā vuṭṭhāsi ṭhānaso

Etena sacca-vajjena / sotthi te hotu sabbadā
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| divasa (m./nt.)       | day; from diva; √div (shine)                                    | 32680/dpd |                                                |
| gelañña (nt.)         | sickness; ill health; [√gilā + na + *ya]                        | 25212/dpd | {{gelaññenā}}bhipīḷito                         |
| abhipīḷita (pp.)      | affected; oppressed                                             | 7965/dpd  | gelaññen{{ābhipīḷito}}                         |
| taññeva (sandhi)      | that very; the self same [taṁ + eva]                           | 29303/dpd | Cundattherena {{taññeva}}                      |
| bhaṇāpeti (pr. caus.) | causes to speak; makes say; caus of bhaṇati                     | 49233/dpd | Cundattherena taññeva {{bhaṇāpetvāna}} sādaraṁ |
| sādaraṁ (ind.)       | with consideration; respectfully                                | 62172/dpd | bhaṇāpetvāna {{sādaraṁ}}                       |
| sammoditvā (abs.)     | having delighted together (with) [saṁ + √mud + *a + itvā]      | 60932/dpd | {{sammoditvā}} ca ābādhā                       |
| ṭhānaso (ind.)        | on the spot; right there; lit. from the place [√ṭhā + ana + so] | 29059/dpd | tamhā vuṭṭhāsi {{ṭhānaso}}                     |

#+begin_quote
Pahīnā te ca ābādhā / tiṇṇannam-pi mahesinaṁ

Magg'āhata-kilesā va / pattānuppatti-dhammataṁ

Etena sacca-vajjena / sotthi te hotu sabbadā
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| tiṇṇaṁ / tiṇṇannaṁ (card.) | dat. or gen. of /ti/                                       | 30430/dpd | {{tiṇṇannam}}-pi mahesinaṁ  |
| mahesi (m.)                 | great sage; mighty seer; [mahā + isi]                      | 52091/dpd | tiṇṇannam-pi {{mahesinaṁ}}  |
| āhata (pp.)                 | struck; beaten; destroyed; [ā + √han + ta]                 | 13179/dpd | Magg'{{āhata}}-kilesā va     |
| patta (pp.)                 | reached; attained; accomplished; pp of pāpuṇāti            | 41851/dpd | {{pattā}}nuppatti-dhammataṁ |
| anuppatti (f.)              | non-arising; non-appearance; lit. not going up [ud + √pad] | 4906/dpd  | patt{{ānuppatti}}-dhammataṁ |
| dhammatā (f.)               | nature; characteristic; attribute                          | 34714/dpd | pattānuppatti-{{dhammataṁ}} |

*** Related :noexport:
**** Wheel 1 by Piyadassi Thera

https://www.accesstoinsight.org/lib/authors/piyadassi/wheel001.html

**** The Bojjhaṅgas: Medicine that Makes All Diseases Disappear (2008)

Chanmyay Myaing Sayadaw

The body is nāma-rūpa

p.5 [19]
: Cittena nīyati loko (SN 1.62)
: Taṇhāya nīyati loko (SN 1.63)

"The world is led around by consciousness / craving."

: “Cittena kho, bhikkhu, loko nīyati, cittena parikassati, cittassa uppannassa
: vasaṁ gacchatī”ti. (AN 4.186)

“Mendicant, the mind leads the world on. The mind drags it around. When the mind
arises, it takes control.”

Visuddhimagga Chapter XIV (Khandhāniddesa)

The body is four kinds of rūpa:

1. kammaja rūpa - kamma-produced form
2. cittaja rūpa - mind-produced form
3. utuja rūpa - temperature-produced form
4. āhāraja rūpa - nutriment-produced form

The bojjhaṅgas affect /cittaja rūpa/

[[http://localhost:4848/suttas/vb6/pli/ms?quote=r%25C5%25ABpa%25E1%25B9%2581%2520cittaja%25E1%25B9%2581&window_type=Sutta+Study][rūpaṁ cittajaṁ]]

... jivhāyatanassa upacayo, kāyāyatanassa upacayo, yaṁ vā panaññampi atthi rūpaṁ
cittajaṁ cittahetukaṁ cittasamuṭṭhānaṁ— idaṁ vuccati “rūpaṁ”. Iti idañca nāmaṁ,
idañca rūpaṁ. Idaṁ vuccati “viññāṇapaccayā nāmarūpaṁ”.

Story: Inge's Tumour (p.20 [34])

**** Visuddhimagga

Question: Where are these Pāli terms found:

kammaja rūpa, cittaja rūpa, utuja rūpa, āhāraja rūpa?

NORBU: These Pāli terms referring to the four types of matter (rūpa) according
to their origin are primarily found in the post-canonical Abhidhamma
commentarial literature, particularly in:

1. Visuddhimagga (The Path of Purification) by Buddhaghosa
2. Abhidhammatthasangaha (Manual of Abhidhamma) by Acariya Anuruddha

These terms describe the four ways material phenomena arise:

- kammaja rūpa: matter produced by kamma
- cittaja rūpa: matter produced by consciousness
- utuja rūpa: matter produced by temperature/heat
- āhāraja rūpa: matter produced by nutrition

The detailed analysis of these concepts is most extensively covered in the
Visuddhimagga's chapters on rūpa, particularly in Chapter XIV (Khandhāniddesa).

Since these are primarily commentarial terms rather than appearing in the
earliest Buddhist texts (Nikāyas), I should note that while I'm confident about
their presence in these later texts, you may want to verify the specific chapter
references I've provided.

[[http://localhost:4848/suttas/e0102n.mul/pli/cst4?quote=cittato%2520j%25C4%2581ta%25E1%25B9%2581%2520cittaja%25E1%25B9%2581&window_type=Sutta+Study][cittato jātaṁ cittajaṁ]]

#+begin_quote
(448.) puna sabbameva rūpaṁ sanidassanakammajādīnaṁ tikānaṁ vasena tividhaṁ
hoti. tattha oḷārike rūpaṁ sanidassanasappaṭighaṁ, sesaṁ anidassanasappaṭighaṁ.
sabbampi sukhumaṁ anidassanaappaṭighaṁ. evaṁ tāva sanidassanattikavasena
tividhaṁ. kammajādittikavasena pana kammato jātaṁ kammajaṁ, tadaññapaccayajātaṁ
akammajaṁ, nakutocijātaṁ neva kammajaṁ nākammajaṁ. cittato jātaṁ cittajaṁ,
tadaññapaccayajātaṁ acittajaṁ, nakutocijātaṁ neva cittajaṁ nācittajaṁ, āhārato
jātaṁ āhārajaṁ, tadaññapaccayajātaṁ anāhārajaṁ, nakutocijātaṁ neva āhārajaṁ
naanāhārajaṁ. ututo jātaṁ utujaṁ, tadaññapaccayajātaṁ anutujaṁ, nakutocijātaṁ
neva utujaṁ naanutujanti evaṁ kammajādittikavasena tividhaṁ.
#+end_quote
**** Bojjhanga Suttas chanted by small Sri Lankan boy Dhammaruwan

[[https://www.youtube.com/watch?v=ghyc9WftU3w][Bojjhanga Suttas chanted by small Sri Lankan boy - YouTube]]

*** Analysis :noexport:
**** Meter

Siloka (Śloka) meter

Boj/jhaṅ/go/ sa/ti/-saṅ/khā/to (8 syllables)
dham/mā/naṁ/ vi/ca/yo/ ta/thā (8 syllables)

**** Bojjhaṅgo sati-saṅkhāto

Line 1:
- Bojjhaṅgo: (nom. sing.) factor of enlightenment (bojjha + aṅga)
- sati-saṅkhāto: (nom. sing.) known as mindfulness (sati + saṅkhāta)
- dhammānaṁ: (gen. plural) of phenomena/states
- vicayo: (nom. sing.) investigation
- tathā: (adv.) likewise, thus

Line 2:
- viriyam: (nom. sing.) energy
- pīti: (nom. sing.) joy/rapture
- passaddhi: (nom. sing.) tranquility
- bojjhaṅgā: (nom. plural) factors of enlightenment
- ca: (conj.) and
- tathā: (adv.) likewise
- pare: (nom. plural) others

Line 3:
- samādhi: (nom. sing.) concentration
- upekkhā: (nom. sing.) equanimity
- bojjhaṅgā: (nom. plural) factors of enlightenment
- satta: (num.) seven
- ete: (dem. pron.) these
- sabba-dassinā: (inst. sing.) by the All-Seeing One

Line 4:
- muninā: (inst. sing.) by the sage
- sammad-akkhātā: (nom. plural) properly declared
- bhāvitā: (nom. plural) developed
- bahulīkatā: (nom. plural) practiced frequently

Line 5:
- saṁvattanti: (pres. 3rd plural) lead to
- abhiññāya: (dat. sing.) for direct knowledge
- nibbānāya: (dat. sing.) for Nibbāna
- ca: (conj.) and
- bodhiyā: (dat. sing.) for enlightenment

Line 6:
- etena: (inst. sing.) by this
- sacca-vajjena: (inst. sing.) truth utterance
- sotthi: (nom. sing.) well-being
- te: (dat. sing.) to you
- hotu: (imp. 3rd sing.) may there be
- sabbadā: (adv.) always

------

Ekasmiṁ samaye nātho
moggallānañ-ca kassapaṁ
Gilāne dukkhite disvā
bojjhaṅge satta desayi

1. Ekasmiṁ
- eka: "one" (numeral)
- smiṁ: locative case singular suffix
- Combined meaning: "at one, in one"

2. samaye
- samaya: "time, occasion"
- e: locative case singular suffix
- Meaning: "at time, on occasion"

3. nātho
- nātha: "protector, lord, refuge" (epithet of the Buddha)
- o: nominative case singular suffix
- Meaning: "the Lord"

4. moggallānañ-ca
- moggallāna: proper name (Moggallāna)
- ñ: accusative case marker
- ca: "and" (conjunction)
- Meaning: "Moggallāna and"

5. kassapaṁ
- kassapa: proper name (Kassapa)
- ṁ: accusative case singular suffix
- Meaning: "Kassapa" (as object)

6. Gilāne
- gilāna: "sick, ill"
- e: accusative case plural suffix
- Meaning: "the sick ones"

7. dukkhite
- dukkhita: "suffering, afflicted"
- e: accusative case plural suffix
- Meaning: "the afflicted ones"

8. disvā
- √dis: "to see"
- tvā: absolutive suffix
- Meaning: "having seen"

9. bojjhaṅge
- bojjhaṅga: "factor of enlightenment"
- e: accusative case plural suffix
- Meaning: "the factors of enlightenment"

10. satta
- "seven" (numeral)
- Meaning: "seven"

11. desayi
- √dis: "to teach, to preach"
- ayi: third person singular past tense suffix
- Meaning: "taught, preached"

Te ca taṁ abhinanditvā
rogā mucciṁsu taṅ-khaṇe

1. Te
- ta: demonstrative pronoun "they, those"
- e: nominative case plural suffix
- Meaning: "they"

2. ca
- conjunction "and"
- Meaning: "and"

3. taṁ
- ta: demonstrative pronoun "that"
- ṁ: accusative case singular suffix
- Meaning: "that" (referring to the teaching)

4. abhinanditvā
- abhi: prefix meaning "towards, thoroughly"
- √nand: "to rejoice, delight in"
- itvā: absolutive suffix
- Meaning: "having rejoiced in, having delighted in"

5. rogā
- roga: "disease, illness"
- ā: ablative case singular suffix
- Meaning: "from illness"

6. mucciṁsu
- √muc: "to release, to free"
- iṁsu: third person plural aorist suffix
- Meaning: "were freed, were released"

7. taṅ-khaṇe
- taṁ: "that"
- khaṇa: "moment, instant"
- e: locative case singular suffix
- Combined as compound: "at that moment"

**** Ekasmiṁ samaye nātho

Ekasmiṁ = in one (locative singular of eka)
samaye = time, occasion (locative singular)
nātho = protector, lord (nominative singular, referring to the Buddha)

moggallānañ-ca = and Moggallāna (accusative singular with conjunction -ca)
kassapaṁ = Kassapa (accusative singular)

gilāne = sick, ill (accusative plural)
dukkhite = suffering (accusative plural)
disvā = having seen (absolutive/gerund of √dis)
bojjhaṅge = factors of enlightenment (accusative plural)
satta = seven (numeral)
desayi = taught (aorist, 3rd person singular of √dis)

te = they (nominative plural)
ca = and
taṁ = that (accusative singular)
abhinanditvā = having rejoiced in (absolutive/gerund of abhi + √nand)
rogā = from disease (ablative singular)
mucciṁsu = were freed (aorist, 3rd person plural of √muc)
taṅ-khaṇe = at that moment (locative singular)

**** Ekadā dhamma-rājā pi

Ekadā = once, at one time (indeclinable)
dhamma-rājā = king of Dhamma (nominative singular compound)
pi = also, even (indeclinable particle)

gelaññena = by illness (instrumental singular)
abhipīḷito = oppressed, afflicted (past participle, nominative singular)

Cundattherena = by Elder Cunda (instrumental singular)
tañ-ñeva = that very same (accusative singular + emphatic particle eva)
bhaṇāpetvāna = having caused to recite (causative absolutive/gerund of √bhaṇ)
sādaraṁ = respectfully (adverb)

sammoditvā = having rejoiced (absolutive/gerund of sam + √mud)
ca = and
ābādhā = from illness (ablative singular)
tamhā = from that (ablative singular)
vuṭṭhāsi = arose, recovered (aorist, 3rd person singular of vuṭṭhāti)
ṭhānaso = immediately (indeclinable)

**** Pahīnā te ca ābādhā

Pahīnā = abandoned, eliminated (past participle, nominative plural)
te = those (nominative plural)
ca = and
ābādhā = illnesses (nominative plural)
tiṇṇannam-pi = of the three (genitive plural + emphatic particle pi)
mahesinaṁ = of the great sages (genitive plural)

magga = path (compound element)
āhata = struck, destroyed (past participle in compound)
kilesā = defilements (nominative plural)
va = like, just as, from iva (indeclinable particle)
pattā = attained (past participle, nominative plural)
anuppatti = non-arising (in compound)
dhammataṁ = state, nature (accusative singular)

**** Magg'āhata-kilesā va

The compound magg'āhata (where apostrophe indicates elision) means "struck/destroyed by the Path"

So the full phrase "Magg'āhata-kilesā va" means "like the defilements destroyed by the Path"

This is a powerful metaphorical comparison in the Bojjhanga Paritta. The line draws a parallel between:
- The way physical illnesses (ābādhā) were eliminated in the case of the three great sages
- How the Noble Path destroys mental defilements (kilesā)

**** pattānuppatti-dhammataṁ

(1) anuppatti -> an + uppatti -> an + ud + √pad + ti -> non-arising
(2) anuppatti -> from anupāpuṇāti -> anu + pa + √ap + ti -> attainment, realization (of)

√pad (go, step)
√ap (reach, attain)

1. patta = attained, reached (past participle of pāpuṇāti)
2. anuppatti = non-arising, non-occurrence (negative compound: an + uppatti)
- an = negative prefix
- uppatti = arising, rebirth, occurrence
3. dhammataṁ = state, nature, condition (accusative singular)

When combined, "pattānuppatti-dhammataṁ" means "reached/attained the state of
non-arising" or "attained the condition of non-recurrence."

For "pattānuppatti-dhammataṁ", I followed this construction:
patta + anuppatti + dhammataṁ
attained the non-arising / non-reoccurring state/condition
anuppatti as [an + ud + √pad]
√pad･3 ya (go, step)

Taking anuppatti as realized/attained [anu + pa + √ap + ti]
it would be "attained the attainment of the natural condition"?

Seems awkward for the double "attained", √ap root

saccānuppatti [sacca + anuppatti] takes that form

In the chanting reference I had this translation: "... just as defilements are demolished by the Path in accordance with step-by-step attainment."
going with √pad (go, step)

https://bhikkhu-manual.github.io/chants/parittas.html#awakening

step-by-step attainment (Wat Marp Jan)
https://youtu.be/IKUDUc__xsI?t=1312

reached the stage of never occurring again (Burmese)
https://youtu.be/G-U8n7--fyU?t=313

one attains what can be attained according to Dhamma (Chinese)
https://youtu.be/XizIU4qKoCk?t=212

On attaining the nature of non-arising
https://youtu.be/WqEh1fO6i0A?t=209

cease to arise forever (Singapore)
https://youtu.be/JHl9WhrqI6w?t=206
