authors:
  gavesako:
    name: Gavesako Bhikkhu
    description: ""
    avatar: assets/images/gavesako.jpg
  gambhiro:
    name: Gambhīro Bhikkhu
    description: ""
    avatar: assets/images/gambhiro.png
  varabho:
    name: Varabho Bhikkhu
    description: ""
    avatar: assets/images/varabho.jpg
  nyanatejo:
    name: Ñāṇatejo Bhikkhu
    description: ""
    avatar: assets/images/nyanatejo.jpg
  mahabodhi:
    name: Mahābodhi Bhikkhu
    description: ""
    avatar: assets/images/mahabodhi.jpg
  bodhirasa:
    name: Bodhirasa Bhikkhu
    description: ""
    avatar: assets/images/bodhirasa.jpg
