authors:
  gavesako:
    name: Gavesako Bhikkhu
    description: ""
    avatar: assets/images/gavesako.jpg
  gambhiro:
    name: Gambhīro Bhikkhu
    description: ""
    avatar: assets/images/gambhiro.png
  varabho:
    name: Varabho Bhikkhu
    description: ""
    avatar: assets/images/varabho.jpg
